server:
  port: 80


spring:
  application:
    name: shoppingmall

  devtools:
    restart:
      enabled: true

    livereload:
      enabled: true

  thymeleaf:
    cache: false

  ####################################
    # 데이터베이스설정
    ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 613986

  ####################################
  # JPA 설정
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: create      # create, update, none, create-drop, validate 실제 개발완료후에는 validate사용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜표기를 스네이크 표기로 변환. 자바는 소문자대문자를 구분하지만(카멜표기) sql은 구분 안하므로 대문자를 _소문자로 바꿔줌(스네이크)
    show-sql: true          # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true    # 포맷 처리해서 보이기. 한줄처리되어있는것을 여러줄로 보기좋게 설정
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용

  #로그인설정
  security:
    user:
      name: test@test.com
      password: 1111

#쿼리에서 물음표로 출력되는 바인드를 추적해서 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
